"""
database.py

all SQLite interaction is here.

"""

import json
import sqlite3
from datetime import datetime, timezone

DB_PATH = "tasks.db"


# connection helper
def get_connection() -> sqlite3.Connection:
    """
    open a connection to the SQLite database:
      - row_factory = sqlite3.Row  -> rows behave like dicts (row["column"])
      - WAL journal mode           -> concurrent reads & writes without blocking
    """
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    return conn


# schema
def init_db() -> None:
    """
    Create the tasks table if it doesn't already exist.
    Called once at application startup.

    Column notes:
      - id          : UUID string generated by the route handler
      - dataset_id  : the 'dataset_id' field from inside the uploaded JSON
      - filename    : original uploaded filename, for display in the UI
      - status      : one of 'pending' | 'processing' | 'completed' | 'failed'
      - result      : JSON string, NULL until the task completes successfully
      - error       : human-readable error message, NULL unless status='failed'
      - created_at  : set once on insert, never updated
      - updated_at  : updated on every status transition
    """
    with get_connection() as conn:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS tasks (
                id          TEXT PRIMARY KEY,
                dataset_id  TEXT NOT NULL,
                filename    TEXT NOT NULL,
                status      TEXT NOT NULL DEFAULT 'pending',
                result      TEXT,
                error       TEXT,
                created_at  TEXT NOT NULL,
                updated_at  TEXT NOT NULL
            )
        """)


# helpers
def _now() -> str:
    """return the current UTC time as an iso string."""
    return datetime.now(timezone.utc).isoformat()


def _row_to_dict(row: sqlite3.Row) -> dict:
    """
    convert a sqlite3.Row to a plain dict
    """
    d = dict(row)
    if d.get("result") is not None:
        d["result"] = json.loads(d["result"])
    return d


# write functions
def create_task(task_id: str, dataset_id: str, filename: str) -> dict:
    """
    insert a new task in 'pending' status and return it as a dict.
    called by the route handler immediately after the file is
    validated, before the task is put on the queue.
    """
    now = _now()
    with get_connection() as conn:
        conn.execute(
            """
            INSERT INTO tasks (id, dataset_id, filename, status, created_at, updated_at)
            VALUES (?, ?, ?, 'pending', ?, ?)
            """,
            (task_id, dataset_id, filename, now, now),
        )
    return get_task(task_id)


def set_processing(task_id: str) -> None:
    """mark a task as processing, called by the worker before computation begins."""
    with get_connection() as conn:
        conn.execute(
            "UPDATE tasks SET status='processing', updated_at=? WHERE id=?",
            (_now(), task_id),
        )


def set_completed(task_id: str, result: dict) -> None:
    """
    mark a task as completed and store the result.
    result dict is serialized to a JSON string for storage.
    """
    with get_connection() as conn:
        conn.execute(
            "UPDATE tasks SET status='completed', result=?, updated_at=? WHERE id=?",
            (json.dumps(result), _now(), task_id),
        )


def set_failed(task_id: str, error: str) -> None:
    """mark a task as failed and store the error message."""
    with get_connection() as conn:
        conn.execute(
            "UPDATE tasks SET status='failed', error=?, updated_at=? WHERE id=?",
            (error, _now(), task_id),
        )


# read functions
def get_task(task_id: str) -> dict | None:
    """
    fetch a single task by ID and returns a dict (with result deserialized)
    or None if no task with that ID exists.
    """
    with get_connection() as conn:
        row = conn.execute(
            "SELECT * FROM tasks WHERE id=?", (task_id,)
        ).fetchone()
    return _row_to_dict(row) if row else None


def get_all_tasks() -> list[dict]:
    """
    fetch all tasks ordered by creation time (newest first).
    """
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT id, dataset_id, filename, status, error, created_at, updated_at
            FROM tasks
            ORDER BY created_at DESC
            """
        ).fetchall()
    return [dict(row) for row in rows]


# startup recovery  
def get_stuck_tasks() -> list[dict]:
    """
    find tasks that were left in 'processing' status from a previous
    server run, these will never complete on their own and must be
    handled during startup recovery.
    """
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT * FROM tasks WHERE status='processing'"
        ).fetchall()
    return [_row_to_dict(row) for row in rows]


def reset_task(task_id: str) -> bool:
    """reset a failed task back to pending so it can be re-enqueued, returns False if not found."""
    with get_connection() as conn:
        cur = conn.execute(
            "UPDATE tasks SET status='pending', error=NULL, updated_at=? WHERE id=? AND status='failed'",
            (_now(), task_id),
        )
    return cur.rowcount > 0


def delete_task(task_id: str) -> bool:
    """delete a task by ID, returns True if a row was deleted, False if not found."""
    with get_connection() as conn:
        cur = conn.execute("DELETE FROM tasks WHERE id=?", (task_id,))
    return cur.rowcount > 0


def get_pending_tasks() -> list[dict]:
    """
    find tasks in 'pending' status.
    """
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT * FROM tasks WHERE status='pending' ORDER BY created_at ASC"
        ).fetchall()
    return [_row_to_dict(row) for row in rows]