"""
database.py

All SQLite interaction lives here. Nothing else in the codebase
touches the database directly — everything goes through these functions.

We use Python's stdlib sqlite3 module (no ORM, no external deps).
The connection is created fresh per call rather than shared globally,
which avoids threading issues when FastAPI's worker and route handlers
both write concurrently.

WAL mode (Write-Ahead Logging) is enabled so readers don't block writers
and writers don't block readers — important since our worker is writing
status updates while the routes are reading task lists.
"""

import json
import sqlite3
from datetime import datetime, timezone

DB_PATH = "tasks.db"


# ── Connection helper ────────────────────────────────────────────────────────

def get_connection() -> sqlite3.Connection:
    """
    Open a connection to the SQLite database with sensible defaults:
      - row_factory = sqlite3.Row  → rows behave like dicts (row["column"])
      - WAL journal mode           → concurrent reads + writes without blocking
      - foreign_keys = ON          → enforce referential integrity (good habit)
    """
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    return conn


# ── Schema ───────────────────────────────────────────────────────────────────

def init_db() -> None:
    """
    Create the tasks table if it doesn't already exist.
    Called once at application startup.

    Column notes:
      - id          : UUID string generated by the route handler
      - dataset_id  : the 'dataset_id' field from inside the uploaded JSON
      - filename    : original uploaded filename, for display in the UI
      - status      : one of 'pending' | 'processing' | 'completed' | 'failed'
      - result      : JSON string, NULL until the task completes successfully
      - error       : human-readable error message, NULL unless status='failed'
      - created_at  : set once on insert, never updated
      - updated_at  : updated on every status transition
    """
    with get_connection() as conn:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS tasks (
                id          TEXT PRIMARY KEY,
                dataset_id  TEXT NOT NULL,
                filename    TEXT NOT NULL,
                status      TEXT NOT NULL DEFAULT 'pending',
                result      TEXT,
                error       TEXT,
                created_at  TEXT NOT NULL,
                updated_at  TEXT NOT NULL
            )
        """)


# ── Helpers ──────────────────────────────────────────────────────────────────

def _now() -> str:
    """Return the current UTC time as an ISO 8601 string."""
    return datetime.now(timezone.utc).isoformat()


def _row_to_dict(row: sqlite3.Row) -> dict:
    """
    Convert a sqlite3.Row to a plain dict, deserializing the 'result'
    field from a JSON string back to a Python dict if present.
    """
    d = dict(row)
    if d.get("result") is not None:
        d["result"] = json.loads(d["result"])
    return d


# ── Write functions ──────────────────────────────────────────────────────────

def create_task(task_id: str, dataset_id: str, filename: str) -> dict:
    """
    Insert a new task in 'pending' status and return it as a dict.
    This is called by the route handler immediately after the file is
    validated, before the task is put on the queue.
    """
    now = _now()
    with get_connection() as conn:
        conn.execute(
            """
            INSERT INTO tasks (id, dataset_id, filename, status, created_at, updated_at)
            VALUES (?, ?, ?, 'pending', ?, ?)
            """,
            (task_id, dataset_id, filename, now, now),
        )
    return get_task(task_id)


def set_processing(task_id: str) -> None:
    """Mark a task as processing. Called by the worker before computation begins."""
    with get_connection() as conn:
        conn.execute(
            "UPDATE tasks SET status='processing', updated_at=? WHERE id=?",
            (_now(), task_id),
        )


def set_completed(task_id: str, result: dict) -> None:
    """
    Mark a task as completed and store the result.
    The result dict is serialized to a JSON string for storage.
    """
    with get_connection() as conn:
        conn.execute(
            "UPDATE tasks SET status='completed', result=?, updated_at=? WHERE id=?",
            (json.dumps(result), _now(), task_id),
        )


def set_failed(task_id: str, error: str) -> None:
    """Mark a task as failed and store the error message."""
    with get_connection() as conn:
        conn.execute(
            "UPDATE tasks SET status='failed', error=?, updated_at=? WHERE id=?",
            (error, _now(), task_id),
        )


# ── Read functions ───────────────────────────────────────────────────────────

def get_task(task_id: str) -> dict | None:
    """
    Fetch a single task by ID. Returns a dict (with result deserialized)
    or None if no task with that ID exists.
    """
    with get_connection() as conn:
        row = conn.execute(
            "SELECT * FROM tasks WHERE id=?", (task_id,)
        ).fetchone()
    return _row_to_dict(row) if row else None


def get_all_tasks() -> list[dict]:
    """
    Fetch all tasks ordered by creation time (newest first).
    The 'result' field is intentionally excluded here to keep the
    list payload small — full results are fetched per-task.
    """
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT id, dataset_id, filename, status, error, created_at, updated_at
            FROM tasks
            ORDER BY created_at DESC
            """
        ).fetchall()
    return [dict(row) for row in rows]


# ── Startup recovery ─────────────────────────────────────────────────────────

def get_stuck_tasks() -> list[dict]:
    """
    Find tasks that were left in 'processing' status from a previous
    server run. These will never complete on their own and must be
    handled during startup recovery.
    """
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT * FROM tasks WHERE status='processing'"
        ).fetchall()
    return [_row_to_dict(row) for row in rows]


def get_pending_tasks() -> list[dict]:
    """
    Find tasks in 'pending' status. On a clean shutdown these shouldn't
    exist (pending tasks are queued in memory and processed before shutdown),
    but if the server crashed before the worker picked them up, they'll
    be sitting here. We re-enqueue them on startup.
    """
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT * FROM tasks WHERE status='pending' ORDER BY created_at ASC"
        ).fetchall()
    return [_row_to_dict(row) for row in rows]